import { MigrationInterface, QueryRunner } from 'typeorm';
import { Quality } from '../Entities/quality.entity';
import { Weapon } from '../Entities/weapon.entity';

export class insertWeapons1613164609643 implements MigrationInterface {
  private readonly WEAPONS = [
    ['Alley Hunter', 'Bow', 4, 'Gacha'],
    ["Amos' Bow", 'Bow', 5, 'Gacha'],
    ['Blackcliff Warbow', 'Bow', 4, 'Starglitter Exchange'],
    ['Compound Bow', 'Bow', 4, 'Crafting'],
    ['Ebony Bow', 'Bow', 3, 'Gacha'],
    ['Favonius Warbow', 'Bow', 4, 'Gacha'],
    ["Hunter's Bow", 'Bow', 1, 'Chest'],
    ['Messenger', 'Bow', 3, 'Chest'],
    ['Prototype Crescent', 'Bow', 4, 'Crafting'],
    ['Raven Bow', 'Bow', 3, 'Gacha'],
    ['Recurve Bow', 'Bow', 3, 'Chest'],
    ['Royal Bow', 'Bow', 4, 'Starglitter Exchange'],
    ['Rust', 'Bow', 4, 'Gacha'],
    ['Sacrificial Bow', 'Bow', 4, 'Gacha'],
    ["Seasoned Hunter's Bow", 'Bow', 2, 'Chest'],
    ["Sharpshooter's Oath", 'Bow', 3, 'Gacha'],
    ['Skyward Harp', 'Bow', 5, 'Gacha'],
    ['Slingshot', 'Bow', 3, 'Gacha'],
    ['The Stringless', 'Bow', 4, 'Gacha'],
    ['The Viridescent Hunt', 'Bow', 4, 'BP Bounty'],
    ['Amber Catalyst', 'Catalyst', 3, 'Gacha'],
    ["Apprentice's Notes", 'Catalyst', 1, 'Chest'],
    ['Blackcliff Agate', 'Catalyst', 4, 'Starglitter Exchange'],
    ['Emerald Orb', 'Catalyst', 3, 'Gacha'],
    ['Eye of Perception', 'Catalyst', 4, 'Gacha'],
    ['Favonius Codex', 'Catalyst', 4, 'Gacha'],
    ['Frostbearer', 'Catalyst', 4, 'Crafting'],
    ['Memory of Dust', 'Catalyst', 5, 'Gacha'],
    ['Lost Prayer to the Sacred Winds', 'Catalyst', 5, 'Gacha'],
    ['Magic Guide', 'Catalyst', 3, 'Gacha'],
    ['Mappa Mare', 'Catalyst', 4, 'Crafting'],
    ['Otherworldly Story', 'Catalyst', 3, 'Gacha'],
    ['Pocket Grimoire', 'Catalyst', 2, 'Chest'],
    ['Prototype Amber', 'Catalyst', 4, 'Crafting'],
    ['Royal Grimoire', 'Catalyst', 4, 'Starglitter Exchange'],
    ['Sacrificial Fragments', 'Catalyst', 4, 'Gacha'],
    ['Skyward Atlas', 'Catalyst', 5, 'Gacha'],
    ['Solar Pearl', 'Catalyst', 4, 'BP Bounty'],
    ['The Widsith', 'Catalyst', 4, 'Gacha'],
    ['Thrilling Tales of Dragon Slayers', 'Catalyst', 3, 'Gacha'],
    ['Twin Nephrite', 'Catalyst', 3, 'Gacha'],
    ['Wine and Song', 'Catalyst', 4, 'Gacha'],
    ['Blackcliff Slasher', 'Claymore', 4, 'Starglitter Exchange'],
    ['Bloodtainted Greatsword', 'Claymore', 3, 'Gacha'],
    ['Debate Club', 'Claymore', 3, 'Gacha'],
    ['Favonius Greatsword', 'Claymore', 4, 'Gacha'],
    ['Ferrous Shadow', 'Claymore', 3, 'Gacha'],
    ['Lithic Blade', 'Claymore', 4, 'Gacha'],
    ["Old Merc's Pal", 'Claymore', 2, 'Chest'],
    ['Prototype Archaic', 'Claymore', 4, 'Crafting'],
    ['Quartz', 'Claymore', 3, 'Gacha'],
    ['Rainslasher', 'Claymore', 4, 'Gacha'],
    ['Royal Greatsword', 'Claymore', 4, 'Starglitter Exchange'],
    ['Sacrificial Greatsword', 'Claymore', 4, 'Gacha'],
    ['Serpent Spine', 'Claymore', 4, 'BP Bounty'],
    ['Skyrider Greatsword', 'Claymore', 3, 'Gacha'],
    ['Skyward Pride', 'Claymore', 5, 'Gacha'],
    ['Snow-Tombed Starsilver', 'Claymore', 4, 'Crafting'],
    ['The Bell', 'Claymore', 4, 'Gacha'],
    ['The Unforged', 'Claymore', 5, 'Gacha'],
    ['Waster Greatsword', 'Claymore', 1, 'Chest'],
    ['White Iron Greatsword', 'Claymore', 3, 'Gacha'],
    ['Whiteblind', 'Claymore', 4, 'Crafting'],
    ["Wolf's Gravestone", 'Claymore', 5, 'Gacha'],
    ["Beginner's Protector", 'Polearm', 1, 'Chest'],
    ['Black Tassel', 'Polearm', 3, 'Gacha'],
    ['Blackcliff Pole', 'Polearm', 4, 'Starglitter Exchange'],
    ['Crescent Pike', 'Polearm', 4, 'Crafting'],
    ['Deathmatch', 'Polearm', 4, 'BP Bounty'],
    ['Dragonspine Spear', 'Polearm', 4, 'Crafting'],
    ["Dragon's Bane", 'Polearm', 4, 'Gacha'],
    ['Favonius Lance', 'Polearm', 4, 'Gacha'],
    ['Halberd', 'Polearm', 3, 'Gacha'],
    ['Iron Point', 'Polearm', 2, 'Chest'],
    ['Lithic Spear', 'Polearm', 4, 'Gacha'],
    ['Primordial Jade Winged-Spear', 'Polearm', 5, 'Gacha'],
    ['Prototype Starglitter', 'Polearm', 4, 'Crafting'],
    ['Royal Spear', 'Polearm', 4, 'Starglitter Exchange'],
    ['Skyward Spine', 'Polearm', 5, 'Gacha'],
    ['Vortex Vanquisher', 'Polearm', 5, 'Gacha'],
    ['White Tassel', 'Polearm', 3, 'Chest'],
    ['Aquila Favonia', 'Sword', 5, 'Gacha'],
    ['Blackcliff Longsword', 'Sword', 4, 'Starglitter Exchange'],
    ['Cool Steel', 'Sword', 3, 'Gacha'],
    ['Dark Iron Sword', 'Sword', 3, 'Gacha'],
    ['Dull Blade', 'Sword', 1, 'Chest'],
    ['Favonius Sword', 'Sword', 4, 'Gacha'],
    ['Festering Desire', 'Sword', 4, 'Story Quest'],
    ['Fillet Blade', 'Sword', 3, 'Gacha'],
    ['Harbinger of Dawn', 'Sword', 3, 'Gacha'],
    ['Iron Sting', 'Sword', 4, 'Crafting'],
    ["Lion's Roar", 'Sword', 4, 'Gacha'],
    ['Prototype Rancour', 'Sword', 4, 'Crafting'],
    ['Royal Longsword', 'Sword', 4, 'Starglitter Exchange'],
    ['Sacrificial Sword', 'Sword', 4, 'Gacha'],
    ['Silver Sword', 'Sword', 2, 'Chest'],
    ['Skyrider Sword', 'Sword', 3, 'Gacha'],
    ['Skyward Blade', 'Sword', 5, 'Gacha'],
    ['Summit Shaper', 'Sword', 5, 'Gacha'],
    ['Sword of Descension', 'Sword', 4, 'Gacha'],
    ['The Alley Flash', 'Sword', 4, 'Gacha'],
    ['The Black Sword', 'Sword', 4, 'BP Bounty'],
    ['The Flute', 'Sword', 4, 'Gacha'],
    ["Traveler's Handy Sword", 'Sword', 3, 'Chest'],
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    const qualities = await queryRunner.manager.find(Quality);
    for (let weapon of this.WEAPONS) {
      await queryRunner.manager.save(
        new Weapon(
          weapon[0].toString(),
          weapon[1].toString(),
          qualities[Number(weapon[2]) - 1],
          weapon[3].toString(),
        ),
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (let weapon of this.WEAPONS) {
      await queryRunner.manager.delete(Weapon, { name: weapon[0].toString() });
    }
  }
}
